/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SystemMetrics } from "./SystemMetrics";
import { SystemMetricsCountArgs } from "./SystemMetricsCountArgs";
import { SystemMetricsFindManyArgs } from "./SystemMetricsFindManyArgs";
import { SystemMetricsFindUniqueArgs } from "./SystemMetricsFindUniqueArgs";
import { DeleteSystemMetricsArgs } from "./DeleteSystemMetricsArgs";
import { SystemMetricsService } from "../systemMetrics.service";
@graphql.Resolver(() => SystemMetrics)
export class SystemMetricsResolverBase {
  constructor(protected readonly service: SystemMetricsService) {}

  async _systemMetricsItemsMeta(
    @graphql.Args() args: SystemMetricsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SystemMetrics])
  async systemMetricsItems(
    @graphql.Args() args: SystemMetricsFindManyArgs
  ): Promise<SystemMetrics[]> {
    return this.service.systemMetricsItems(args);
  }

  @graphql.Query(() => SystemMetrics, { nullable: true })
  async systemMetrics(
    @graphql.Args() args: SystemMetricsFindUniqueArgs
  ): Promise<SystemMetrics | null> {
    const result = await this.service.systemMetrics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SystemMetrics)
  async deleteSystemMetrics(
    @graphql.Args() args: DeleteSystemMetricsArgs
  ): Promise<SystemMetrics | null> {
    try {
      return await this.service.deleteSystemMetrics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
